DROP TABLE IF EXISTS Test;

CREATE TABLE Test
(
    ID INT IDENTITY(1000, 10),
    Data VARCHAR(50)
);

INSERT INTO Test (Data) VALUES ('Row 1');
INSERT INTO Test (Data) VALUES ('Row 2');
INSERT INTO Test (Data) VALUES ('Row 3');

SELECT @@IDENTITY;
SELECT IDENT_CURRENT('Test')