using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

public class Person
{
    // Id is auto-generated by db
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }
    public int Age { get; set; }
}


[Route("[controller]")]
[ApiController]
public class PersonsController : ControllerBase
{
    private readonly ApplicationDbContext _context;

    public PersonsController(ApplicationDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public ActionResult<IEnumerable<Person>> Get()
    {
        var persons = _context.Persons.ToList();
        return Ok(persons);
    }

    [HttpPost]
    public ActionResult<Person> Post([FromBody] Person person)
    {
        if (person == null)
        {
            return BadRequest("Invalid data");
        }

        _context.Persons.Add(person);
        _context.SaveChanges();

        return Ok(new Person()
        {
            Id = person.Id,
            Name = person.Name,
            Age = person.Age,
        });
    }
}
